# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'RootStatisticWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(521, 260)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(40, 30, 171, 31))
        self.comboBox.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.pushButton_logout = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_logout.setGeometry(QtCore.QRect(350, 150, 112, 32))
        self.pushButton_logout.setFocusPolicy(QtCore.Qt.StrongFocus)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/log-out.png"), QtGui.QIcon.Disabled, QtGui.QIcon.Off)
        self.pushButton_logout.setIcon(icon)
        self.pushButton_logout.setObjectName("pushButton_logout")
        self.pushButton_statistic = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_statistic.setGeometry(QtCore.QRect(260, 90, 112, 32))
        self.pushButton_statistic.setFocusPolicy(QtCore.Qt.WheelFocus)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icon/tongji-2.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.pushButton_statistic.setIcon(icon1)
        self.pushButton_statistic.setObjectName("pushButton_statistic")
        self.pushButton_back = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_back.setGeometry(QtCore.QRect(210, 150, 112, 32))
        self.pushButton_back.setFocusPolicy(QtCore.Qt.StrongFocus)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icon/back.png"), QtGui.QIcon.Disabled, QtGui.QIcon.Off)
        self.pushButton_back.setIcon(icon2)
        self.pushButton_back.setObjectName("pushButton_back")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 521, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.comboBox.setItemText(0, _translate("MainWindow", "--请选择统计类别--"))
        self.comboBox.setItemText(1, _translate("MainWindow", "按人员统计"))
        self.comboBox.setItemText(2, _translate("MainWindow", "按部门统计"))
        self.comboBox.setItemText(3, _translate("MainWindow", "按杂志名称统计"))
        self.comboBox.setItemText(4, _translate("MainWindow", "按杂志类别统计"))
        self.pushButton_logout.setText(_translate("MainWindow", "Logout"))
        self.pushButton_statistic.setText(_translate("MainWindow", "统计"))
        self.pushButton_statistic.setShortcut(_translate("MainWindow", "Return"))
        self.pushButton_back.setText(_translate("MainWindow", "back"))
import resource_rc
