# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'RootStatisticWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(395, 246)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(110, 40, 171, 31))
        self.comboBox.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.pushButton_statistic = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_statistic.setGeometry(QtCore.QRect(140, 130, 112, 32))
        self.pushButton_statistic.setFocusPolicy(QtCore.Qt.WheelFocus)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/tongji-2.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.pushButton_statistic.setIcon(icon)
        self.pushButton_statistic.setObjectName("pushButton_statistic")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 395, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.comboBox.setItemText(0, _translate("MainWindow", "--请选择统计类别--"))
        self.comboBox.setItemText(1, _translate("MainWindow", "按人员统计"))
        self.comboBox.setItemText(2, _translate("MainWindow", "按部门统计"))
        self.comboBox.setItemText(3, _translate("MainWindow", "按杂志名称统计"))
        self.comboBox.setItemText(4, _translate("MainWindow", "按杂志类别统计"))
        self.pushButton_statistic.setText(_translate("MainWindow", "统计"))
        self.pushButton_statistic.setShortcut(_translate("MainWindow", "Return"))
import resource_rc
